### ISSUE TITLE
add raw file feature 

### ISSUE THREAD

**Issue by mohammed-sec2010** [ZephrFish/BurpFeed#4]
Hi
add raw file feature to send  all raw files in a directory to burp suite

**Comment by MantisSTS** [comment]
Hi @mohammed-sec2010 

I'm not sure I understand the requirements or what you aim to achieve with this. Can you give me a scenario where you'd want to do this?

Thanks

**Comment by ZephrFish** [comment]
if you wanted to do that surely running it in a for loop would work better? 

for x in $(ls); do BurpFeed -filename $x; done

**Comment by mohammed-sec2010** [comment]
Hi
I want to passs this raw file to burpsuite :
GET /dvwa/vulnerabilities/sqli/ HTTP/1.1
Host: 192.168.1.154
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://192.168.1.154/dvwa/vulnerabilities/sqli/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: security=low; PHPSESSID=1ee8cec2b7dd183de5e8e5e3a8eb2154
Connection: close
X-Burp-Comment:   |  

more info:
https://grimhacker.com/2015/04/07/raw-http-requests-to-burp-proxy/

**Comment by ZephrFish** [comment]
That's not what this is for, surely you can just open that in repeater?

**Comment by mohammed-sec2010** [comment]
you can add headers option in burpfeeed , we can pass the additional headers to your script ,this is a good idea

**Comment by ZephrFish** [comment]
https://bitbucket.org/snippets/grimhacker/yK7A based off the blog post you linked looks like there's already a tool to do this.

**Comment by mohammed-sec2010** [comment]
there is a problem in rawtoproxy.py : Failed to send request. <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
I fixed it temporarily by export  this PYTHONHTTPSVERIFY=0 in env 
it would be great if you add this option to your tool

**Comment by MantisSTS** [comment]
I'll take a look at this soon @mohammed-sec2010

**Comment by mohammed-sec2010** [comment]
my idea is I  want to import logs file to burp suite to compare between old file and new file

**Comment by ZephrFish** [comment]
Sounds like you want a completely different tool, why not write one?

**Comment by ZephrFish** [comment]
Closing as the request is for a completely different feature to what this tool is for, comparer and diff will do what you're looking to achieve. An alternative is to write your own tool to do what you want to do.
